overblog_graphql:
    definitions:
        schema:
            main:
                query: AppSchema
                mutation: AppMutation

        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/*"
                    suffix: null
