Book:
  type: object
  config:
    fields:
      id:
        type: Int!
      title:
        type: String!
      pdfFile:
        type: String
      downloadable:
        type: Boolean
      coverFile:
        type: String
      author:
        type: String!
      readAt:
        type: DateTime
